shop/account/urls.py
from django.urls import path
from account import views

app_name = 'account'
urlpatterns = [
     path('register/', views.register, name='register'),
     path('login/', views.login, name='login'),
     path('logout/', views.logout, name='logout'),
]

shop/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('buy/', views.buy, name='buy'),
    path('call/', views.call, name='call'),
]

shop/product/urls.py
from django.urls import path
from product import views


app_name = 'product'
urlpatterns = [
    path('', views.product, name='product'),
    path('productCreate/', views.productCreate, name='productCreate'),
    path('productRead/<int:productId>/', views.productRead, name='productRead'),
    path('productUpdate/<int:productId>/', views.productUpdate, name='productUpdate'),
    path('productDelete/<int:productId>/', views.productDelete, name='productDelete'),
    path('order/', views.order, name='order'),
    ]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls', namespace='product')),
    path('main/', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    re_path('.*', views.main),
]

shop/main/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls.base import reverse

def main(request):
    '''
    Render the main page
    '''
    context = {'like':'Django 很棒'}
    return render(request, 'main/main.html', context)
def about(request):
    '''
    Render the about page
    '''
    return render(request, 'main/about.html')
# Create your views here.
def buy(request):
    '''
    Render the buy page
    '''
    return render(request, 'main/buy.html')
def call(request):
    '''
    Render the call page
    '''
    return render(request, 'main/call.html')
def admin_required(func):
    def auth(request, *args, **kwargs):
        if not request.user.is_superuser:
            messages.error(request, '請以管理者身份登入')
            return redirect(reverse('account:login') + '?next=' + request.get_full_path())
        return func(request, *args, **kwargs)
    return auth

shop/main/templates/main/about.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Candy Shop</title>
    <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
        <link rel="stylesheet" href="{% static 'main/about.css' %}">
  </head>
  <body>
  <div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
  
  <div id="content" class='ab'>
     <h1>關於糖果小舖Candy</h1>
      <p class='abb'>
      為了看到顧客歡樂的笑容，我們樂於創新，並將我們的創新分享給所有的朋友，讓大家都能從分享中得到歡樂。<br><br>
    
    糖，我們做了30年，顧客眼中的糖，對我們而言不只是糖，而是一份信任和託付。<br>
    因此，天然、健康是我們唯一的訴求，除了良好的品質控管。<br>
    創新，也是我們不斷追求的核心，因為我們樂於分享，所以一直追求更新與更好。<br>
    分享，在於看見每位顧客歡樂的笑容，也證明了我們存在的價值。<br><br>
    
    從小舖，走進大型百貨，我們都不曾離開過，每一個期待的笑容，我們都相當重視。<br>
    如家人、朋友般的存在，陪伴您每個歡笑的時刻，也豐富精彩您的生活。<br><br>
    
    因為你們，我們一直都在。<br>
    無論何時得意，都給您真摯的問候，不論每分每秒，都更專注於您的需求。<br>
    您的每一個笑容，都是我們前進的動力。<br><br>
    
    糖果小舖，不只是一個品牌，更是為了歡樂與歡笑而存在<br><br>
     </p>
      <div class="jpg">
       <img class="jp" src="{% static 'main/img/no1-1.jpg'%}" alt="pure css3 slider" />
      <img  class="jp" src="{% static 'main/img/no2-1.jpg'%}" alt="pure css3 slider" />
      <img class="jp" src="{% static 'main/img/no3-1.jpg'%}" alt="pure css3 slider" />
       </div>
     
</div>  <!-- wrapper -->
  </body>
</html>

shop/main/templates/main/base.html
<!doctype html>
{% load staticfiles %}
<head>
    <title>Candy Shop</title>
    <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'main/css/base.css' %}">
        {% block css %}{% endblock %}
  </head>
  <body>
  <div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
  
  <div id="content">
    <h2>Candy Shop -- {% block heading %}{% endblock %}</h2>
    {% include 'main/messages.html' %}
    {% block content %}{% endblock %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    {% block script %}{% endblock %}
</div>  <!-- wrapper -->
  </body>
</html>

shop/main/templates/main/buy.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Candy Shop</title>
    <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'main/css/buy.css' %}">
  </head>
  <body>
  <div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
  
  <div id="content">
  <p class="problem1">會員常見問題</p>
  <ul class="menu1">
    <li>該如何加入會員</li>
    <li>忘記密碼怎麼辦？</li>
    <li>忘記第一次購物時所填寫的E-mail信箱？</li>
    <li>該如何修改個人資料及密碼</li>
    <li>訂閱及取消電子報</li>
  </ul>
  <p class="problem2">購物常見問題</p>
  <ul class="menu2">
    <li>如何購買糖果小舖商品？</li>
    <li>有哪些付款方式？</li>
    <li>請問有貨到付款嗎？</li>
    <li>臨櫃匯款告知匯款資訊方式？</li>
    <li>如何查詢訂單狀態？</li>
    <li>糖果小舖有實體門市嗎？</li>
    <li>糖果小舖門市營業時間？</li>
  </ul>
  <p class="problem3">寄件與配送</p>
  <ul class="menu3">
    <li>宅配運費如何計算？</li>
    <li>配送方式？</li>
    <li>收貨可以指定時間嗎？</li>
    <li>訂購完成後最快多久可以收到呢？</li>
    <li>宅配沒收到怎麼辦？</li>
  </ul>
  <p class="problem4">保存與品嘗方式</p>
  <ul class="menu4">
    <li>甜點保存方式？</li>
    <li>如何品嘗？</li>

  </ul>
  <p class="problem5">匯款資訊與發票相關</p>
  <ul class="menu5">
    <li>糖果小舖匯款資訊？</li>
    <li>公司行號如何取得三聯式統一發票？</li>
    <li>收到發票後，發現統編/抬頭有錯誤怎麼辦？</li>
  </ul>
  <p class="problem6">退換貨與退款</p>
  <ul class="menu6">
  <li>實際收到的品項跟當初的訂單不一樣or嚴重瑕疵，請問要如何處理？</li>
  </ul>
</div>  <!-- wrapper -->
  </body>
</html>

shop/main/templates/main/call.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Candy Shop</title>
    <meta charset="utf-8">
        <link rel="stylesheet" href="{% static 'main/css/call.css' %}">
  </head>
  <body>
  <div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
   <div id="content">
  <h1 id="k1">門市資訊</h1>
  <h2 class="no5"> ※台中美術門市※</h2>
 
    <p class="no1">
 <img class="jp" src="{% static 'main/img/loca1.jpg'%}" alt="pure css3 slider" />
  <p  class="no1"><a href="https://www.google.com.tw/maps/place/403%E5%8F%B0%E4%B8%AD%E5%B8%82%E8%A5%BF%E5%8D%80%E4%BA%94%E6%AC%8A%E8%A5%BF%E8%B7%AF%E4%B8%80%E6%AE%B5122%E8%99%9F/@24.1402748,120.6585475,17z/data=!3m1!4b1!4m5!3m4!1s0x34693da6af7ba7c7:0xd9ab7ae29c52f886!8m2!3d24.1402748!4d120.6607362">門市位址：台中市五權西路一段122號</a></p>
   <p class="no1">
  門市專線：(04) 2375 - 4848<br>
  營業時間：<br>
  週一 - 週日10:00-21:00<br>
  <br>
  </p>
  </p>
  
   <h2 class="no5"> ※台中市政門市※</h2>
  <p class="no2"><img class="jp" src="{% static 'main/img/loca2.jpg'%}" alt="pure css3 slider" /></p>
  <p class="no2"><a href="https://www.google.com.tw/maps/place/407%E5%8F%B0%E4%B8%AD%E5%B8%82%E8%A5%BF%E5%B1%AF%E5%8D%80%E5%8F%B0%E7%81%A3%E5%A4%A7%E9%81%93%E4%B8%89%E6%AE%B562%E8%99%9F/@24.1621299,120.6492933,17z/data=!3m1!4b1!4m5!3m4!1s0x34693d8efdb056af:0xa2155b5952dc798d!8m2!3d24.1621299!4d120.651482">門市位址：台中市台灣大道三段62號</a></p>
  <p class="no2">
  門市專線：(04) 2313 - 8777<br>
  營業時間：<br>
  週一 - 週五 11:30-19:00<br>
  週六 - 週日 11:00-20:00<br>
  <br>
  </p>
  
  <h2 class="no5"> ※台北大安門市※</h2>
  <p class="no3"><img class="jp" src="{% static 'main/img/loca3.jpg'%}" alt="pure css3 slider" /></p>
  <p class="no3"><a href="https://www.google.com.tw/maps/place/106%E5%8F%B0%E5%8C%97%E5%B8%82%E5%A4%A7%E5%AE%89%E5%8D%80%E5%A4%A7%E5%AE%89%E8%B7%AF%E4%B8%80%E6%AE%B5105%E8%99%9F1/@25.0401129,121.5456287,19z/data=!3m1!4b1!4m5!3m4!1s0x3442abd0664c9c4b:0x3f203686d4c8a2e!8m2!3d25.0401129!4d121.5461759">門市位址：台北市大安區大安路一段105號1樓</a></p>
  <p class="no3">
  門市專線：(02) 2711 - 3303<br>
  營業時間：<br>
  週一 - 週五 13:00 - 20:30<br>
  週六 - 週日 12:30 - 20:00<br>
  <br>
  </p>
  
  <h1 id="k2">聯絡我們</h1>
  <h2 class="no5"> ※宅配服務※</h2>
  <p class="no4"><img class="jp" src="{% static 'main/img/loca4.jpg'%}" alt="pure css3 slider" /></p>
  <p class="no4">
  訂購專線：(04) 2358 - 8897<br>
  聯絡信箱：candy@candy.com<br>
  服務時間：09:30 - 18:00<br>
  
  </p>
  </div>
  </body>
</html>

shop/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Candy shop</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
  </head>
  <body>
  
  <div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
  
  <div id="content">
     <table border="0">
      <tr>
          <td> <div class="pic">
      <div>
      <img src="{% static 'main/img/1.jpg'%}" alt="pure css3 slider" />
      <span class="info"></span>
      </div> 
      <div>
        <img src="{% static 'main/img/2.jpg'%}" alt="pure css3 slider" />
        <span class="info"></span>
      </div> 
      <div>
        <img src="{% static 'main/img/3.jpg'%}" alt="pure css3 slider" />
        <span class="info"></span>
      </div> 
      <div>
        <img src="{% static 'main/img/4.jpg'%}" alt="pure css3 slider" />
        <span class="info"></span>
      </div> 
      <div>
        <img src="{% static 'main/img/5.jpg'%}" alt="pure css3 slider" />
        <span class="info"></span>
      </div> 
    </div>
    </td>
    </tr>
      <tr>
        <td class="new"><h1 >新年系列</h1></td>
      </tr>
       <tr >
        <td class='s2'><img class="s1" src="{% static 'main/img/11.jpg'%}"></td>
         <td class="s3"><img class="s1" src="{% static 'main/img/13.jpeg'%}"></td>
          <td class="s4"><img class="s1" src="{% static 'main/img/12.jpg'%}"></td>
      </tr>
    </table>
</div>  <!-- wrapper -->
  </body>
</html>

shop/main/templates/main/menu.html
<ul id="candy">
  <li class="candy"><a href="{% url 'main:main' %}">Candy Shop</a></li>
</ul>
<ul id="menu">
  <li><a id="m" href="{% url 'product:product' %}">最新商品 &nbsp;&nbsp;&nbsp; /</a></li>
  <li><a id="m" href="{% url 'main:about' %}">關於我們&nbsp;&nbsp;&nbsp; /</a></li>
  <li><a id="m" href="{% url 'main:buy' %}">購物資訊&nbsp;&nbsp;&nbsp; /</a></li>
  <li><a id="m" href="{% url 'main:call' %}">聯絡資訊&nbsp;&nbsp;&nbsp; /</a></li>
  {% if user.is_authenticated %}
    <li><a id="m" href="{% url 'account:logout' %}">登出 ({{ user.username }})&nbsp;&nbsp;&nbsp; /</a></li>
  {% else %}
    <li><a id="m" href="{% url 'account:register' %}">註冊&nbsp;&nbsp;&nbsp; /</a></li>
    <li><a id="m" href="{% url 'account:login' %}">登入&nbsp;&nbsp;&nbsp; /</a></li>
  {% endif %}
</ul>

shop/main/templates/main/message.html
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}

shop/main/templates/main/messages.html
{% for message in messages %}
  <p class="{{ message.tags }}">{{ message }}</p>
{% endfor %}