shop/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('', views.main, name='main'),
    path('about/', views.about, name='about'),
    path('buy/', views.buy, name='buy'),
    path('call/', views.call, name='call'),
]

shop/product/urls.py
from django.urls import path
from product import views


app_name = 'product'
urlpatterns = [
    path('', views.product, name='product'),
    path('productCreate/', views.productCreate, name='productCreate'),
    path('productRead/<int:productId>/', views.productRead, name='productRead'),
    path('productUpdate/<int:productId>/', views.productUpdate, name='productUpdate'),
    path('productDelete/<int:productId>/', views.productDelete, name='productDelete'),
    path('order/', views.order, name='order'),
    ]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('product.urls', namespace='product')),
    path('main/', include('main.urls', namespace='main')),
    path('account/', include('account.urls', namespace='account')),
    re_path('.*', views.main),
]

shop/product/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=128, unique=True)
    content = models.TextField()
    pubDateTime = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)

    
    def __str__(self):
        return self.title

    class Meta:
        ordering = ['-pubDateTime']
        
class Comment(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    content = models.CharField(max_length=128)
    pubDateTime = models.DateTimeField(auto_now_add=True)



    def __str__(self):
        return self.product.title + '-' + str(self.id)
    class Meta:
        ordering = ['pubDateTime']
        
class Order(models.Model):
    Name = models.CharField(max_length=128)
    adress = models.CharField(max_length=128)
    phone = models.CharField(max_length=12)
    number= models.IntegerField()



    def __str__(self):
        return self.Name
# Create your models here.

shop/product/forms.py
from django import forms
from product.models import Product
from product.models import Order
class ProductForm(forms.ModelForm):
    title = forms.CharField(label='產品名稱', max_length=128)
    content = forms.CharField(label='內容', widget=forms.Textarea)
    price = forms.CharField(label='價格', widget=forms.NumberInput())
    class Meta:
        model = Product
        fields = ['title', 'content','price']

class OrderForm(forms.ModelForm):
    Name = forms.CharField(label='姓名', max_length=128)
    adress = forms.CharField(label='地址', max_length=128)
    phone = forms.CharField(label='聯絡電話',max_length=12)
    number = forms.CharField(label='購買數量', widget=forms.NumberInput())

    class Meta:
        model = Order
        fields = ['Name', 'adress','phone','number']

shop/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from product.models import Product, Comment
from product.forms import ProductForm
from main.views import admin_required
from product.forms import OrderForm

def product(request):
    '''
    Render the product page
    '''
    products = {}
    for product in Product.objects.all():
        products.update({product:Comment.objects.filter(product=product)})
    context = {'products':products}
    return render(request, 'product/product.html', context)

@admin_required
def productCreate(request):
    '''
    Create a new product instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the product page
    '''
    template = 'product/productCreateUpdate.html'
    if request.method == 'GET':
        print(ProductForm())
        return render(request, template, {'productForm':ProductForm()})
    # POST
    productForm = ProductForm(request.POST)
    if not productForm.is_valid():
        return render(request, template, {'productForm':productForm})
    
    productForm.save()
    messages.success(request, '文章已新增')
    return redirect('product:product')
def productRead(request, productId):
    '''
    Read an product
        1. Get the "product" instance using "productId"; redirect to the 404 page if not found
        2. Render the productRead template with the product instance and its
           associated comments
    '''
    product = get_object_or_404(Product, id=productId)
    context = {
        'product': product,
        'comments': Comment.objects.filter(product=product)
    }
    return render(request, 'product/productRead.html', context)

@admin_required
def productUpdate(request, productId):
    '''
    Update the product instance:
        1. Get the product to update; redirect to 404 if not found
        2. Render a bound form if the method is GET
        3. If the form is valid, save it to the model, otherwise render a
           bound form with error messages
    '''
    product = get_object_or_404(Product, id=productId)
    template = 'product/productCreateUpdate.html'
    if request.method == 'GET':
        productForm = ProductForm(instance=product)
        return render(request, template, {'productForm':productForm})

    # POST
    productForm = ProductForm(request.POST, instance=product)
    if not productForm.is_valid():
        return render(request, template, {'productForm':productForm})

    productForm.save()
    messages.success(request, '文章已修改') 
    return redirect('product:productRead', productId=productId)

@admin_required
def productDelete(request, productId):
    '''
    Delete the product instance:
        1. Render the product page if the method is GET
        2. Get the product to delete; redirect to 404 if not found
    '''
    if request.method == 'GET':
        return product(request)

    # POST
    product = get_object_or_404(Product, id=productId)
    product.delete()
    messages.success(request, '文章已刪除')  
    return redirect('product:product')

def order(request):
    '''
    Create a new order instance
        1. If method is GET, render an empty form
        2. If method is POST, perform form validation and display error messages if the form is invalid
        3. Save the form to the model and redirect the user to the order page
    '''
    template = 'product/order.html'
    if request.method == 'GET':
        return render(request, template, {'orderForm':OrderForm()})
    # POST
    orderForm = OrderForm(request.POST)
    if not orderForm.is_valid():
        return render(request, template, {'orderForm':orderForm})
    
    orderForm.save()
    messages.success(request, '購買資訊已新增')
    return redirect('product:product')

shop/product/templates/product/order.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
<title>Candy Shop</title>
<meta charset="utf-8">
<link rel="stylesheet" href="{% static 'product/css/order.css' %}">
<link rel="stylesheet" href="{% static 'product/css/product.css' %}">
</head>
<body>
<div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
  
<div id="conten">
<h2>聯絡人資訊</h2>
<form method="post" action="{% url 'product:order' %}">
  {% csrf_token %}
  {{ orderForm.as_p }}
  <label for=date>選擇商品:&nbsp;</label>    
        <select name=room class="choice">
        <option value=room  class='oo'>抹茶巧克力</option>
          <option value=room  class='oo'>葡萄軟糖</option>
          <option value=room  class='oo'> 北極熊驚喜糖 </option>
          <option value=room  class='oo'>婚禮棉花糖</option>
          <option value=room class='oo'>金幣糖</option>
        </select>
  <br>
  <input class="btn" type="submit" value="送出">
  <a class="btn" href="{% url 'product:product' %}">取消</a>
</form>
</div>
</div>
</body>
</html>

shop/product/templates/product/product.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Candy Shop</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/product.css' %}">
  </head>
  <body>
   <div id="wrapper">
  <nav>{% include 'main/menu.html' %}</nav>
  <header></header>
  
  <div id="content">
  <h1 class='we'>歡迎來到Candy Shop</h1>
    <p>{% for message in messages %}</p>
      <p class="{{ message.tags }}">{{ message }}</p>
        {% endfor %} 
      <table border='1' class='table'>
    <tr>
    <td class="it">
    <img class='b3' src="{% static 'main/img/16.jpeg'%}" alt="pure css3 slider" />
    <img class='b2' src="{% static 'main/img/15.jpeg'%}" alt="pure css3 slider" />
     <img class='b1' src="{% static 'main/img/13.jpeg'%}" alt="pure css3 slider" /></td>
     <td class="td">{% if user.is_superuser %}
    <p><a class="btn" href="{% url 'product:productCreate' %}">新增產品</a></p> 
    {% endif %}
    {% for product, comments in products.items %}
      <h3 class="inlineBlock"><a href="{% url 'product:productRead' product.id %}">{{ product.title }}</a></h3>
      {% if user.is_superuser %}
      <form class="inlineBlock" method="post" action="{% url 'product:productDelete' product.id %}">
        {% csrf_token %}
        <input class="btn" type="submit" value="刪除">
      </form>
      {% endif %}
      <div class="productContent">{{ product.content|linebreaks|truncatechars_html:30}}</div>
      <p>價格：{{product.price }}</p>
      <p><a class="btn" href="{% url 'product:order' %}">購買商品</a></p>
      {% for comment in comments %}
        <div class="commentDiv">
          <span class="comment">{{ comment.content }}</span>
          <br>
          <span class="commentTime">{{ comment.pubDateTime|date:'m月d日 H:i' }}</span>
        </div>
      {% endfor %}
      <hr>
    {% endfor %}
    </td>
    </tr>
 </table>
</div>  <!-- wrapper -->
    
  </body>
</html>

shop/product/templates/product/productCreateUpdate.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
   <title>Candy Shop</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main1.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/product.css' %}">
  </head>
  <body>
  <div id="wrapper">
  <nav>
    {% include 'main/menu.html' %}
    {% if productForm.instance.id %}
    </nav>
  <header></header>
  <div id="conten" >
      <h2>修改產品</h2>
      <form method="post" action="{% url 'product:productUpdate' productForm.instance.id %}">
    {% else %}
      <h2>新增產品</h2>
      <form method="post" action="{% url 'product:productCreate' %}">
    {% endif %}
      {% csrf_token %}
      {{ productForm.as_p }}
     <input class="btn" type="submit" value="送出">
     <a class="btn" href="{% url 'product:product' %}">放棄</a>
    </form>
    </div>
    </div>
  </body>
</html>

shop/product/templates/product/productRead.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>Candy Shop</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'main/css/main1.css' %}">
    <link rel="stylesheet" href="{% static 'product/css/product.css' %}">
  </head>
  <body>
   <div id="wrapper">
  <nav>
  {% include 'main/menu.html' %}
  {% include 'main/messages.html' %}
    </nav>
  <header></header>
  
  <div id="conten" >
  
    <h3 class="inlineBlock">{{ product.title }}</h3>
    {% if user.is_superuser %}
    <a class="btn inlineBlock" href="{% url 'product:productUpdate' product.id %}">修改</a>
    {% endif %}
    <p>發表時間：{{ product.pubDateTime|date:'Y-m-d H:i' }}</p>
    <div class="productContent">{{ product.content|linebreaks }}</div>
    {% for comment in comments %}
      <div class="commentDiv">
        <span class="comment">{{ comment.content }}</span>
        <br>
        <span class="commentTime">{{ comment.pubDateTime|date:'Y-m-d H:i'}}</span>
      </div>
    {% endfor %}
    <p>價錢:{{ product.price }}</p>
    </div>
    </div>
  </body>
</html>